Greeting.create(massege: 'Hello, world!')
Greeting.create(massege: 'Hello, Develpers!')
Greeting.create(massege: 'Hello, Rails!')
Greeting.create(massege: 'Hello, React!')
Greeting.create(massege: 'Hello, Redux!')
Greeting.create(massege: 'Hello, JavaScript!')